services:
  apache:
    container_name: cms-less-apache
    build: .
    ports:
      - "9090:80"
    networks:
      - database
    volumes:
      - ./src/:/var/www/html/

  mariadb:
    container_name: cms-less-mariadb
    image: mariadb
    volumes:
      - db-data:/etc/data
    environment:
      - MARIADB_ROOT_PASSWORD=qwerty
    networks:
      - database

  phpmyadmin:
    container_name: cms-less-phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - database
    ports:
      - "9091:80"
    environment:
      - PMA_HOST=cms-less-mariadb

volumes:
  db-data:

networks:
  database: {}